/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package DocRegistration.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

/**
 * The base model interface for the Document service. Represents a row in the &quot;document_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link DocRegistration.model.impl.DocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DocRegistration.model.impl.DocumentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Document
 * @see DocRegistration.model.impl.DocumentImpl
 * @see DocRegistration.model.impl.DocumentModelImpl
 * @generated
 */
@ProviderType
public interface DocumentModel extends BaseModel<Document> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document model instance should use the {@link Document} interface instead.
	 */

	/**
	 * Returns the primary key of this document.
	 *
	 * @return the primary key of this document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document.
	 *
	 * @param primaryKey the primary key of this document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the doc ID of this document.
	 *
	 * @return the doc ID of this document
	 */
	public long getDocId();

	/**
	 * Sets the doc ID of this document.
	 *
	 * @param docId the doc ID of this document
	 */
	public void setDocId(long docId);

	/**
	 * Returns the file ID of this document.
	 *
	 * @return the file ID of this document
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this document.
	 *
	 * @param fileId the file ID of this document
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the user ID of this document.
	 *
	 * @return the user ID of this document
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this document.
	 *
	 * @param userId the user ID of this document
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this document.
	 *
	 * @return the user uuid of this document
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this document.
	 *
	 * @param userUuid the user uuid of this document
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the req_name of this document.
	 *
	 * @return the req_name of this document
	 */
	@AutoEscape
	public String getReq_name();

	/**
	 * Sets the req_name of this document.
	 *
	 * @param req_name the req_name of this document
	 */
	public void setReq_name(String req_name);

	/**
	 * Returns the req_email of this document.
	 *
	 * @return the req_email of this document
	 */
	@AutoEscape
	public String getReq_email();

	/**
	 * Sets the req_email of this document.
	 *
	 * @param req_email the req_email of this document
	 */
	public void setReq_email(String req_email);

	/**
	 * Returns the sign_email of this document.
	 *
	 * @return the sign_email of this document
	 */
	@AutoEscape
	public String getSign_email();

	/**
	 * Sets the sign_email of this document.
	 *
	 * @param sign_email the sign_email of this document
	 */
	public void setSign_email(String sign_email);

	/**
	 * Returns the doc_type of this document.
	 *
	 * @return the doc_type of this document
	 */
	@AutoEscape
	public String getDoc_type();

	/**
	 * Sets the doc_type of this document.
	 *
	 * @param doc_type the doc_type of this document
	 */
	public void setDoc_type(String doc_type);

	/**
	 * Returns the doc_status of this document.
	 *
	 * @return the doc_status of this document
	 */
	@AutoEscape
	public String getDoc_status();

	/**
	 * Sets the doc_status of this document.
	 *
	 * @param doc_status the doc_status of this document
	 */
	public void setDoc_status(String doc_status);

	/**
	 * Returns the doc_deadline of this document.
	 *
	 * @return the doc_deadline of this document
	 */
	@AutoEscape
	public String getDoc_deadline();

	/**
	 * Sets the doc_deadline of this document.
	 *
	 * @param doc_deadline the doc_deadline of this document
	 */
	public void setDoc_deadline(String doc_deadline);

	/**
	 * Returns the doc_description of this document.
	 *
	 * @return the doc_description of this document
	 */
	@AutoEscape
	public String getDoc_description();

	/**
	 * Sets the doc_description of this document.
	 *
	 * @param doc_description the doc_description of this document
	 */
	public void setDoc_description(String doc_description);

	/**
	 * Returns the file_name of this document.
	 *
	 * @return the file_name of this document
	 */
	@AutoEscape
	public String getFile_name();

	/**
	 * Sets the file_name of this document.
	 *
	 * @param file_name the file_name of this document
	 */
	public void setFile_name(String file_name);

	/**
	 * Returns the file_type of this document.
	 *
	 * @return the file_type of this document
	 */
	@AutoEscape
	public String getFile_type();

	/**
	 * Sets the file_type of this document.
	 *
	 * @param file_type the file_type of this document
	 */
	public void setFile_type(String file_type);

	/**
	 * Returns the file_blob of this document.
	 *
	 * @return the file_blob of this document
	 */
	public Blob getFile_blob();

	/**
	 * Sets the file_blob of this document.
	 *
	 * @param file_blob the file_blob of this document
	 */
	public void setFile_blob(Blob file_blob);

	/**
	 * Returns the file_md5 of this document.
	 *
	 * @return the file_md5 of this document
	 */
	@AutoEscape
	public String getFile_md5();

	/**
	 * Sets the file_md5 of this document.
	 *
	 * @param file_md5 the file_md5 of this document
	 */
	public void setFile_md5(String file_md5);

	/**
	 * Returns the req_date created of this document.
	 *
	 * @return the req_date created of this document
	 */
	@AutoEscape
	public String getReq_dateCreated();

	/**
	 * Sets the req_date created of this document.
	 *
	 * @param req_dateCreated the req_date created of this document
	 */
	public void setReq_dateCreated(String req_dateCreated);

	/**
	 * Returns the req_date modified of this document.
	 *
	 * @return the req_date modified of this document
	 */
	@AutoEscape
	public String getReq_dateModified();

	/**
	 * Sets the req_date modified of this document.
	 *
	 * @param req_dateModified the req_date modified of this document
	 */
	public void setReq_dateModified(String req_dateModified);

	/**
	 * Returns the req_signature of this document.
	 *
	 * @return the req_signature of this document
	 */
	@AutoEscape
	public String getReq_signature();

	/**
	 * Sets the req_signature of this document.
	 *
	 * @param req_signature the req_signature of this document
	 */
	public void setReq_signature(String req_signature);

	/**
	 * Returns the sign_name of this document.
	 *
	 * @return the sign_name of this document
	 */
	@AutoEscape
	public String getSign_name();

	/**
	 * Sets the sign_name of this document.
	 *
	 * @param sign_name the sign_name of this document
	 */
	public void setSign_name(String sign_name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DocRegistration.model.Document document);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DocRegistration.model.Document> toCacheModel();

	@Override
	public DocRegistration.model.Document toEscapedModel();

	@Override
	public DocRegistration.model.Document toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}