/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com._42Penguins.gosign.model.impl;

import aQute.bnd.annotation.ProviderType;

import com._42Penguins.gosign.model.EntKey;
import com._42Penguins.gosign.service.EntKeyLocalServiceUtil;

/**
 * The extended model base implementation for the EntKey service. Represents a row in the &quot;genkey_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntKeyImpl}.
 * </p>
 *
 * @author Raziman Dom
 * @see EntKeyImpl
 * @see EntKey
 * @generated
 */
@ProviderType
public abstract class EntKeyBaseImpl extends EntKeyModelImpl implements EntKey {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ent key model instance should use the {@link EntKey} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EntKeyLocalServiceUtil.addEntKey(this);
		}
		else {
			EntKeyLocalServiceUtil.updateEntKey(this);
		}
	}
}