/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com._42Penguins.gosign.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

/**
 * The base model interface for the EntFileUpload service. Represents a row in the &quot;fileupload_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com._42Penguins.gosign.model.impl.EntFileUploadModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com._42Penguins.gosign.model.impl.EntFileUploadImpl}.
 * </p>
 *
 * @author Raziman Dom
 * @see EntFileUpload
 * @see com._42Penguins.gosign.model.impl.EntFileUploadImpl
 * @see com._42Penguins.gosign.model.impl.EntFileUploadModelImpl
 * @generated
 */
@ProviderType
public interface EntFileUploadModel extends BaseModel<EntFileUpload> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ent file upload model instance should use the {@link EntFileUpload} interface instead.
	 */

	/**
	 * Returns the primary key of this ent file upload.
	 *
	 * @return the primary key of this ent file upload
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ent file upload.
	 *
	 * @param primaryKey the primary key of this ent file upload
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the file ID of this ent file upload.
	 *
	 * @return the file ID of this ent file upload
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this ent file upload.
	 *
	 * @param fileId the file ID of this ent file upload
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the doc ID of this ent file upload.
	 *
	 * @return the doc ID of this ent file upload
	 */
	public long getDocId();

	/**
	 * Sets the doc ID of this ent file upload.
	 *
	 * @param docId the doc ID of this ent file upload
	 */
	public void setDocId(long docId);

	/**
	 * Returns the file_name of this ent file upload.
	 *
	 * @return the file_name of this ent file upload
	 */
	@AutoEscape
	public String getFile_name();

	/**
	 * Sets the file_name of this ent file upload.
	 *
	 * @param file_name the file_name of this ent file upload
	 */
	public void setFile_name(String file_name);

	/**
	 * Returns the file_type of this ent file upload.
	 *
	 * @return the file_type of this ent file upload
	 */
	@AutoEscape
	public String getFile_type();

	/**
	 * Sets the file_type of this ent file upload.
	 *
	 * @param file_type the file_type of this ent file upload
	 */
	public void setFile_type(String file_type);

	/**
	 * Returns the file_blob of this ent file upload.
	 *
	 * @return the file_blob of this ent file upload
	 */
	public Blob getFile_blob();

	/**
	 * Sets the file_blob of this ent file upload.
	 *
	 * @param file_blob the file_blob of this ent file upload
	 */
	public void setFile_blob(Blob file_blob);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EntFileUpload entFileUpload);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EntFileUpload> toCacheModel();

	@Override
	public EntFileUpload toEscapedModel();

	@Override
	public EntFileUpload toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}