/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com._42Penguins.gosign.service.base;

import com._42Penguins.gosign.model.EntKey;
import com._42Penguins.gosign.service.EntKeyService;
import com._42Penguins.gosign.service.persistence.EntDocPersistence;
import com._42Penguins.gosign.service.persistence.EntFileUploadPersistence;
import com._42Penguins.gosign.service.persistence.EntKeyPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the ent key remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com._42Penguins.gosign.service.impl.EntKeyServiceImpl}.
 * </p>
 *
 * @author Raziman Dom
 * @see com._42Penguins.gosign.service.impl.EntKeyServiceImpl
 * @see com._42Penguins.gosign.service.EntKeyServiceUtil
 * @generated
 */
public abstract class EntKeyServiceBaseImpl extends BaseServiceImpl
	implements EntKeyService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com._42Penguins.gosign.service.EntKeyServiceUtil} to access the ent key remote service.
	 */

	/**
	 * Returns the ent doc local service.
	 *
	 * @return the ent doc local service
	 */
	public com._42Penguins.gosign.service.EntDocLocalService getEntDocLocalService() {
		return entDocLocalService;
	}

	/**
	 * Sets the ent doc local service.
	 *
	 * @param entDocLocalService the ent doc local service
	 */
	public void setEntDocLocalService(
		com._42Penguins.gosign.service.EntDocLocalService entDocLocalService) {
		this.entDocLocalService = entDocLocalService;
	}

	/**
	 * Returns the ent doc remote service.
	 *
	 * @return the ent doc remote service
	 */
	public com._42Penguins.gosign.service.EntDocService getEntDocService() {
		return entDocService;
	}

	/**
	 * Sets the ent doc remote service.
	 *
	 * @param entDocService the ent doc remote service
	 */
	public void setEntDocService(
		com._42Penguins.gosign.service.EntDocService entDocService) {
		this.entDocService = entDocService;
	}

	/**
	 * Returns the ent doc persistence.
	 *
	 * @return the ent doc persistence
	 */
	public EntDocPersistence getEntDocPersistence() {
		return entDocPersistence;
	}

	/**
	 * Sets the ent doc persistence.
	 *
	 * @param entDocPersistence the ent doc persistence
	 */
	public void setEntDocPersistence(EntDocPersistence entDocPersistence) {
		this.entDocPersistence = entDocPersistence;
	}

	/**
	 * Returns the ent file upload local service.
	 *
	 * @return the ent file upload local service
	 */
	public com._42Penguins.gosign.service.EntFileUploadLocalService getEntFileUploadLocalService() {
		return entFileUploadLocalService;
	}

	/**
	 * Sets the ent file upload local service.
	 *
	 * @param entFileUploadLocalService the ent file upload local service
	 */
	public void setEntFileUploadLocalService(
		com._42Penguins.gosign.service.EntFileUploadLocalService entFileUploadLocalService) {
		this.entFileUploadLocalService = entFileUploadLocalService;
	}

	/**
	 * Returns the ent file upload remote service.
	 *
	 * @return the ent file upload remote service
	 */
	public com._42Penguins.gosign.service.EntFileUploadService getEntFileUploadService() {
		return entFileUploadService;
	}

	/**
	 * Sets the ent file upload remote service.
	 *
	 * @param entFileUploadService the ent file upload remote service
	 */
	public void setEntFileUploadService(
		com._42Penguins.gosign.service.EntFileUploadService entFileUploadService) {
		this.entFileUploadService = entFileUploadService;
	}

	/**
	 * Returns the ent file upload persistence.
	 *
	 * @return the ent file upload persistence
	 */
	public EntFileUploadPersistence getEntFileUploadPersistence() {
		return entFileUploadPersistence;
	}

	/**
	 * Sets the ent file upload persistence.
	 *
	 * @param entFileUploadPersistence the ent file upload persistence
	 */
	public void setEntFileUploadPersistence(
		EntFileUploadPersistence entFileUploadPersistence) {
		this.entFileUploadPersistence = entFileUploadPersistence;
	}

	/**
	 * Returns the ent key local service.
	 *
	 * @return the ent key local service
	 */
	public com._42Penguins.gosign.service.EntKeyLocalService getEntKeyLocalService() {
		return entKeyLocalService;
	}

	/**
	 * Sets the ent key local service.
	 *
	 * @param entKeyLocalService the ent key local service
	 */
	public void setEntKeyLocalService(
		com._42Penguins.gosign.service.EntKeyLocalService entKeyLocalService) {
		this.entKeyLocalService = entKeyLocalService;
	}

	/**
	 * Returns the ent key remote service.
	 *
	 * @return the ent key remote service
	 */
	public EntKeyService getEntKeyService() {
		return entKeyService;
	}

	/**
	 * Sets the ent key remote service.
	 *
	 * @param entKeyService the ent key remote service
	 */
	public void setEntKeyService(EntKeyService entKeyService) {
		this.entKeyService = entKeyService;
	}

	/**
	 * Returns the ent key persistence.
	 *
	 * @return the ent key persistence
	 */
	public EntKeyPersistence getEntKeyPersistence() {
		return entKeyPersistence;
	}

	/**
	 * Sets the ent key persistence.
	 *
	 * @param entKeyPersistence the ent key persistence
	 */
	public void setEntKeyPersistence(EntKeyPersistence entKeyPersistence) {
		this.entKeyPersistence = entKeyPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EntKeyService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EntKey.class;
	}

	protected String getModelClassName() {
		return EntKey.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = entKeyPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com._42Penguins.gosign.service.EntDocLocalService.class)
	protected com._42Penguins.gosign.service.EntDocLocalService entDocLocalService;
	@BeanReference(type = com._42Penguins.gosign.service.EntDocService.class)
	protected com._42Penguins.gosign.service.EntDocService entDocService;
	@BeanReference(type = EntDocPersistence.class)
	protected EntDocPersistence entDocPersistence;
	@BeanReference(type = com._42Penguins.gosign.service.EntFileUploadLocalService.class)
	protected com._42Penguins.gosign.service.EntFileUploadLocalService entFileUploadLocalService;
	@BeanReference(type = com._42Penguins.gosign.service.EntFileUploadService.class)
	protected com._42Penguins.gosign.service.EntFileUploadService entFileUploadService;
	@BeanReference(type = EntFileUploadPersistence.class)
	protected EntFileUploadPersistence entFileUploadPersistence;
	@BeanReference(type = com._42Penguins.gosign.service.EntKeyLocalService.class)
	protected com._42Penguins.gosign.service.EntKeyLocalService entKeyLocalService;
	@BeanReference(type = EntKeyService.class)
	protected EntKeyService entKeyService;
	@BeanReference(type = EntKeyPersistence.class)
	protected EntKeyPersistence entKeyPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}