/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package DocRegistration.model.impl;

import DocRegistration.model.GenKey;
import DocRegistration.model.GenKeyModel;
import DocRegistration.model.GenKeySoap;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the GenKey service. Represents a row in the &quot;genkey_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link GenKeyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GenKeyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GenKeyImpl
 * @see GenKey
 * @see GenKeyModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class GenKeyModelImpl extends BaseModelImpl<GenKey>
	implements GenKeyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a gen key model instance should use the {@link GenKey} interface instead.
	 */
	public static final String TABLE_NAME = "genkey_data";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userId", Types.BIGINT },
			{ "key_version", Types.BIGINT },
			{ "key_dateCreated", Types.VARCHAR },
			{ "privatekey_Data", Types.VARCHAR },
			{ "publickey_Data", Types.VARCHAR },
			{ "salt_Data", Types.VARCHAR },
			{ "vector_Data", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("key_version", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("key_dateCreated", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("privatekey_Data", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publickey_Data", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("salt_Data", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vector_Data", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table genkey_data (userId LONG not null primary key,key_version LONG,key_dateCreated VARCHAR(75) null,privatekey_Data VARCHAR(75) null,publickey_Data VARCHAR(75) null,salt_Data VARCHAR(75) null,vector_Data VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table genkey_data";
	public static final String ORDER_BY_JPQL = " ORDER BY genKey.userId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY genkey_data.userId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(DocRegistration.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.DocRegistration.model.GenKey"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(DocRegistration.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.DocRegistration.model.GenKey"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GenKey toModel(GenKeySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GenKey model = new GenKeyImpl();

		model.setUserId(soapModel.getUserId());
		model.setKey_version(soapModel.getKey_version());
		model.setKey_dateCreated(soapModel.getKey_dateCreated());
		model.setPrivatekey_Data(soapModel.getPrivatekey_Data());
		model.setPublickey_Data(soapModel.getPublickey_Data());
		model.setSalt_Data(soapModel.getSalt_Data());
		model.setVector_Data(soapModel.getVector_Data());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GenKey> toModels(GenKeySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<GenKey> models = new ArrayList<GenKey>(soapModels.length);

		for (GenKeySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(DocRegistration.service.util.ServiceProps.get(
				"lock.expiration.time.DocRegistration.model.GenKey"));

	public GenKeyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GenKey.class;
	}

	@Override
	public String getModelClassName() {
		return GenKey.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("userId", getUserId());
		attributes.put("key_version", getKey_version());
		attributes.put("key_dateCreated", getKey_dateCreated());
		attributes.put("privatekey_Data", getPrivatekey_Data());
		attributes.put("publickey_Data", getPublickey_Data());
		attributes.put("salt_Data", getSalt_Data());
		attributes.put("vector_Data", getVector_Data());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long key_version = (Long)attributes.get("key_version");

		if (key_version != null) {
			setKey_version(key_version);
		}

		String key_dateCreated = (String)attributes.get("key_dateCreated");

		if (key_dateCreated != null) {
			setKey_dateCreated(key_dateCreated);
		}

		String privatekey_Data = (String)attributes.get("privatekey_Data");

		if (privatekey_Data != null) {
			setPrivatekey_Data(privatekey_Data);
		}

		String publickey_Data = (String)attributes.get("publickey_Data");

		if (publickey_Data != null) {
			setPublickey_Data(publickey_Data);
		}

		String salt_Data = (String)attributes.get("salt_Data");

		if (salt_Data != null) {
			setSalt_Data(salt_Data);
		}

		String vector_Data = (String)attributes.get("vector_Data");

		if (vector_Data != null) {
			setVector_Data(vector_Data);
		}
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public long getKey_version() {
		return _key_version;
	}

	@Override
	public void setKey_version(long key_version) {
		_key_version = key_version;
	}

	@JSON
	@Override
	public String getKey_dateCreated() {
		if (_key_dateCreated == null) {
			return StringPool.BLANK;
		}
		else {
			return _key_dateCreated;
		}
	}

	@Override
	public void setKey_dateCreated(String key_dateCreated) {
		_key_dateCreated = key_dateCreated;
	}

	@JSON
	@Override
	public String getPrivatekey_Data() {
		if (_privatekey_Data == null) {
			return StringPool.BLANK;
		}
		else {
			return _privatekey_Data;
		}
	}

	@Override
	public void setPrivatekey_Data(String privatekey_Data) {
		_privatekey_Data = privatekey_Data;
	}

	@JSON
	@Override
	public String getPublickey_Data() {
		if (_publickey_Data == null) {
			return StringPool.BLANK;
		}
		else {
			return _publickey_Data;
		}
	}

	@Override
	public void setPublickey_Data(String publickey_Data) {
		_publickey_Data = publickey_Data;
	}

	@JSON
	@Override
	public String getSalt_Data() {
		if (_salt_Data == null) {
			return StringPool.BLANK;
		}
		else {
			return _salt_Data;
		}
	}

	@Override
	public void setSalt_Data(String salt_Data) {
		_salt_Data = salt_Data;
	}

	@JSON
	@Override
	public String getVector_Data() {
		if (_vector_Data == null) {
			return StringPool.BLANK;
		}
		else {
			return _vector_Data;
		}
	}

	@Override
	public void setVector_Data(String vector_Data) {
		_vector_Data = vector_Data;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			GenKey.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GenKey toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (GenKey)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GenKeyImpl genKeyImpl = new GenKeyImpl();

		genKeyImpl.setUserId(getUserId());
		genKeyImpl.setKey_version(getKey_version());
		genKeyImpl.setKey_dateCreated(getKey_dateCreated());
		genKeyImpl.setPrivatekey_Data(getPrivatekey_Data());
		genKeyImpl.setPublickey_Data(getPublickey_Data());
		genKeyImpl.setSalt_Data(getSalt_Data());
		genKeyImpl.setVector_Data(getVector_Data());

		genKeyImpl.resetOriginalValues();

		return genKeyImpl;
	}

	@Override
	public int compareTo(GenKey genKey) {
		long primaryKey = genKey.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GenKey)) {
			return false;
		}

		GenKey genKey = (GenKey)obj;

		long primaryKey = genKey.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<GenKey> toCacheModel() {
		GenKeyCacheModel genKeyCacheModel = new GenKeyCacheModel();

		genKeyCacheModel.userId = getUserId();

		genKeyCacheModel.key_version = getKey_version();

		genKeyCacheModel.key_dateCreated = getKey_dateCreated();

		String key_dateCreated = genKeyCacheModel.key_dateCreated;

		if ((key_dateCreated != null) && (key_dateCreated.length() == 0)) {
			genKeyCacheModel.key_dateCreated = null;
		}

		genKeyCacheModel.privatekey_Data = getPrivatekey_Data();

		String privatekey_Data = genKeyCacheModel.privatekey_Data;

		if ((privatekey_Data != null) && (privatekey_Data.length() == 0)) {
			genKeyCacheModel.privatekey_Data = null;
		}

		genKeyCacheModel.publickey_Data = getPublickey_Data();

		String publickey_Data = genKeyCacheModel.publickey_Data;

		if ((publickey_Data != null) && (publickey_Data.length() == 0)) {
			genKeyCacheModel.publickey_Data = null;
		}

		genKeyCacheModel.salt_Data = getSalt_Data();

		String salt_Data = genKeyCacheModel.salt_Data;

		if ((salt_Data != null) && (salt_Data.length() == 0)) {
			genKeyCacheModel.salt_Data = null;
		}

		genKeyCacheModel.vector_Data = getVector_Data();

		String vector_Data = genKeyCacheModel.vector_Data;

		if ((vector_Data != null) && (vector_Data.length() == 0)) {
			genKeyCacheModel.vector_Data = null;
		}

		return genKeyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{userId=");
		sb.append(getUserId());
		sb.append(", key_version=");
		sb.append(getKey_version());
		sb.append(", key_dateCreated=");
		sb.append(getKey_dateCreated());
		sb.append(", privatekey_Data=");
		sb.append(getPrivatekey_Data());
		sb.append(", publickey_Data=");
		sb.append(getPublickey_Data());
		sb.append(", salt_Data=");
		sb.append(getSalt_Data());
		sb.append(", vector_Data=");
		sb.append(getVector_Data());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("DocRegistration.model.GenKey");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>key_version</column-name><column-value><![CDATA[");
		sb.append(getKey_version());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>key_dateCreated</column-name><column-value><![CDATA[");
		sb.append(getKey_dateCreated());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>privatekey_Data</column-name><column-value><![CDATA[");
		sb.append(getPrivatekey_Data());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>publickey_Data</column-name><column-value><![CDATA[");
		sb.append(getPublickey_Data());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>salt_Data</column-name><column-value><![CDATA[");
		sb.append(getSalt_Data());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vector_Data</column-name><column-value><![CDATA[");
		sb.append(getVector_Data());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = GenKey.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			GenKey.class
		};
	private long _userId;
	private long _key_version;
	private String _key_dateCreated;
	private String _privatekey_Data;
	private String _publickey_Data;
	private String _salt_Data;
	private String _vector_Data;
	private GenKey _escapedModel;
}